#!/usr/bin/env python3
import argparse
import requests
import subprocess
import tempfile


def find_tarball(assets):
    suffices = (
        "linux-amd64.tar.gz",
        "x86_64-unknown-linux-musl.tar.gz",
    )
    for asset in assets:
        if any(asset["name"].endswith(s) for s in suffices):
            return asset["browser_download_url"]

    raise ValueError(", ".join(x["name"] for x in assets))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("repo")
    parser.add_argument("files", nargs="*")
    args = parser.parse_args()

    response = requests.get(f"https://api.github.com/repos/{args.repo}/releases/latest")
    response.raise_for_status()
    assets = (response.json()["assets"])
    url = find_tarball(assets)

    with tempfile.NamedTemporaryFile(suffix=".tar.gz") as t:
        subprocess.run(("wget", "--no-verbose", "-O", t.name, url), check=True)
        subprocess.run(("tar", "-C", "/usr/local/bin", "-xf", t.name, *args.files), check=True)


if __name__ == '__main__':
    main()
