#!/usr/bin/env python3
import argparse
import requests
import subprocess
import tempfile


def find_deb(assets):
    for asset in assets:
        if asset["name"].endswith("x86_64.deb") or asset["name"].endswith("amd64.deb"):
            return asset["browser_download_url"]

    raise ValueError(", ".join(x["name"] for x in assets))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("repo")
    args = parser.parse_args()

    response = requests.get(f"https://api.github.com/repos/{args.repo}/releases/latest")
    response.raise_for_status()
    assets = (response.json()["assets"])
    url = find_deb(assets)

    with tempfile.NamedTemporaryFile(suffix=".deb") as t:
        subprocess.run(("wget", "--no-verbose", "-O", t.name, url), check=True)
        subprocess.run(("dpkg", "-i", t.name), check=True)


if __name__ == '__main__':
    main()
