#!/usr/bin/python3
import argparse
import os

def main():
    parser = argparse.ArgumentParser()
    # Ignored, sudo always keeps cwd
    parser.add_argument("--keep-cwd", action="store_true")
    parser.add_argument("--user")
    parser.add_argument("program", nargs="?")
    parser.add_argument("arguments", nargs="*")
    args = parser.parse_args()

    sudo_args = ["sudo"] + (["-u", args.user] if args.user else []) + [args.program or "-s"] + args.arguments
    os.execvp("sudo", sudo_args)

if __name__ == "__main__":
    main()
