#!/usr/bin/python
import argparse
import os
import sys

def main():
    parser = argparse.ArgumentParser()
    # Ignored, sudo always keeps cwd
    parser.add_argument("--keep-cwd", action="store_true")
    parser.add_argument("--user")
    args, rest = parser.parse_known_args()

    sudo_args = ["sudo"] + (["-u", args.user] if args.user else []) + [args.program or "-s"] + rest
    os.execvp("sudo", sudo_args)

if __name__ == "__main__":
    main()
